### ISSUE TITLE
Ratings model and managing M2M relationships

### ISSUE THREAD

**Issue by foresmac** [patrickolaughlin/ChipyMentorship#2]
I think the design of the Ratings needs some work, but I think it would be easy to clean up and would make it easier to calculate the overall rating for a beer or brewpub.

**Comment by patrickolaughlin** [comment]
Reworked Review model, removed beer & brewpub m2m from Review, added reviews to Beer and Brewpub models.  Also removed email field, changed username field to user from Review.  Updated Brewpubs.serializers, Brewpubs.views and Brewpubs.permissions to work with the changes.
